apiVersion: jenkins.io/v1
kind: App
metadata:
  annotations:
    jenkins.io/chart-description: Secure your Jenkins X pipeline using Anchore
    jenkins.io/chart-repository: http://chartmuseum-jx.35.197.97.96.nip.io
  creationTimestamp: null
  labels:
    chart: jx-app-anchore-1.0.0
    jenkins.io/app-name: jx-app-anchore
    jenkins.io/app-version: 1.0.0
  name: jx-app-anchore-jx-app-anchore
spec: {}
