{{- if and (hasKey .Requirements "repository") (eq .Requirements.repository "bucketrepo") }}
enabled: false
{{- else }}
enabled: true

service:
  annotations:
    fabric8.io/expose: "false"
{{- end }}

